[tool.ruff]
line-length = 88
target-version = "py311"
exclude =["migrations"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "TID", "ANN"] 
ignore = ["ANN101", "ANN102", "ANN003", "ANN002", "ANN401"]
