# Generated by Django 5.2.5 on 2025-09-10 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
        ('rank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('submited_at', models.DateTimeField(auto_now_add=True)),
                ('output', models.TextField()),
                ('time_used', models.FloatField()),
                ('memory_used', models.IntegerField()),
                ('veredict', models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error'), ('NE', 'Not Evaluated')], default='NE')),
                ('exercise_languge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.exerciselanguage')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank.rank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submited_at'],
                'indexes': [models.Index(fields=['rank'], name='submission__rank_id_ef4d69_idx'), models.Index(fields=['time_used'], name='submission__time_us_977c1f_idx'), models.Index(fields=['user'], name='submission__user_id_e3b30e_idx'), models.Index(fields=['veredict'], name='submission__veredic_e86ba3_idx'), models.Index(fields=['memory_used'], name='submission__memory__6694ce_idx')],
            },
        ),
    ]
