# Generated by Django 5.2.5 on 2025-09-10 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='submission',
            name='submission__rank_id_ef4d69_idx',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='rank',
        ),
    ]
