# Generated by Django 5.2.5 on 2025-09-08 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True)),
                ('preloaded', models.TextField()),
                ('test_cases', models.TextField()),
                ('test_example_case', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timeout', models.IntegerField(choices=[(100, 'Low'), (200, 'Medium'), (500, 'High')], default=100)),
                ('memory_limit', models.IntegerField(choices=[(64, 'Low'), (128, 'Medium'), (512, 'High')], default=64)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_language', to='exercise.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('exercises', models.ManyToManyField(through='language.ExerciseLanguage', to='exercise.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exerciselanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_language', to='language.language'),
        ),
        migrations.AddConstraint(
            model_name='exerciselanguage',
            constraint=models.UniqueConstraint(fields=('exercise', 'language'), name='unique_language_exercise'),
        ),
    ]
