# Generated by Django 5.2.5 on 2025-11-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('position', models.IntegerField(unique=True)),
                ('description', models.TextField(null=True)),
                ('min_score', models.SmallIntegerField(default=1)),
                ('max_score', models.SmallIntegerField(default=10)),
                ('color', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rank',
                'verbose_name_plural': 'Ranks',
                'ordering': ['-position'],
            },
        ),
    ]
