# Generated by Django 5.2.5 on 2025-09-10 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
        ('rank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exercise',
            name='exercise_ex_created_fceaa4_idx',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='created_by',
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['user'], name='exercise_ex_user_id_b94632_idx'),
        ),
    ]
